# Cloudflare Pages build configuration
# This file configures how Cloudflare Pages builds your Hugo site

# Build command
[build]
  command = "hugo --minify"
  publish = "public"
  
# Environment variables for Hugo
[build.environment]
  HUGO_VERSION = "0.147.4"
  NODE_VERSION = "18"  
# Note: For Cloudflare Pages, the wrangler.toml is mainly for local development
# Actual build configuration is set in the Cloudflare Pages dashboard
# or via GitHub Actions workflow
