# Cloudflare Pages build configuration
# This file configures how Cloudflare Pages builds your Hugo site

# Build command
build:
  command: "hugo --minify"
  publish: "public"
  
# Environment variables for Hugo
environment:
  HUGO_VERSION: "0.147.4"
  NODE_VERSION: "18"
  
# Preview deployments configuration
preview:
  command: "hugo --buildDrafts --buildFuture --minify"
  
# Redirects and headers
_redirects: |
  # Redirect old URLs if needed
  /old-path/* /new-path/:splat 301
  
  # SPA fallback
  /* /index.html 200

_headers: |
  # Security headers
  /*
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: strict-origin-when-cross-origin
    Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:
    
  # Cache static assets
  /assets/*
    Cache-Control: public, max-age=31536000, immutable
    
  # Cache images
  /images/*
    Cache-Control: public, max-age=31536000
    
  # RSS feed
  /index.xml
    Content-Type: application/rss+xml; charset=utf-8
